### ISSUE TITLE
请问本项目有捐助通道吗？

### ISSUE THREAD

**Issue by Endle** [7sDream/firelomo#1]
RT，比如微信收款码，支付宝收款码，或者github sponsor 之类的。

**Comment by 7sDream** [comment]
其实我最近已经不太使用 flomo 了，当时只是注册体验了几天。
主要是 API 这个功能需要付费，不是很符合我的理念，所以没有继续使用。

当时为了体验 API 功能，但发现没有人弄 firefox 扩展，就临时写了这个项目。
但因为现在不太用了，如果有 Bug，或者后续官方 API 变更了，我会不会继续跟进维护这个项目其实挺不确定的。

基于以上原因，所以目前暂时没有什么赞助项目的渠道，应该也不计划弄，毕竟也没有长期维护计划。

我记得 [flomo plus](https://github.com/it5200/flomoPlus) 其实后来也支持了 firefox 的，它功能更全，而且使用人数比较多，大概率维护也更加活跃，可以去看一下。

**Comment by Endle** [comment]
> 我记得 [flomo plus](https://github.com/it5200/flomoPlus) 其实后来也支持了 firefox 的，它功能更全，而且使用人数比较多，大概率维护也更加活跃，可以去看一下。

https://github.com/it5200/flomoPlus/issues/86

Flomo Plus 在 Mozilla 上下架了。我安装后测试了一下，在 Firefox 下有 bug. 我在试着找问题所在，但是暂时还没有什么头绪。

我对JS代码就懂一点。在我粗浅看来，firelomo 的代码质量比 flomo plus 好一些

**Comment by 7sDream** [comment]
原来如此，那在 flomo plus 重新上架之前就继续用着 firelomo 呗（现在应该是正常能用的吧？），倒也不用考虑项目捐款之类的事情。

flomo 的 API 很简单，应该也不会有什么变化；如果遇到啥  Bug，也照常提 Issue 报就行，大概率还是会修的，就是可能不太及时，比如要等到周末。

**Comment by Endle** [comment]
现在我用 firelomo ，体验非常好

相比与 flomo 的 API 变化 （我感觉他们短期内不太会有变化），我倒觉得 Firefox 的更新导致 breaking change 的可能更大一点。不过我现在在 Firefox Nightly 里使用 firelomo ，没有任何问题。短期内应该也不会有什么问题了
