### ISSUE TITLE
memos 与flomo相似，可否改下扩展使用

### ISSUE THREAD

**Issue by firstuanl** [7sDream/firelomo#2]
memos https://github.com/justmemos/memos
docker https://hub.docker.com/r/neosmemo/memos

谢谢

**Comment by 7sDream** [comment]
理论上，如果这个项目和 flomo 的 API 完全一致，那去掉 API URL 的检查逻辑后理论上是可以的用的。

但看上去这是一个可以自己部署的服务，因为扩展需要[声明自己可以作用的域名范围](https://github.com/7sDream/firelomo/blob/master/manifest.json#L45)，我不太希望为了支持各种服务而直接声明通配域名。

比较合理的方式是你 Fork 一下这个项目，然后按需修改。

**Comment by firstuanl** [comment]
谢谢，只在option.html那边找到判断，`pattern="^https://flomoapp\.com/[0-9a-zA-Z/]+/$"`，这个处理了，但是点发送时，弹出没有网络或网址错误，

域名范围，已声明
